[package]
name = "delharc"
version = "0.1.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2018"
exclude = ["tests/**/*.lzh"]#, "tests/**/*.rs"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["lh1", "lz"]
lh1 = []
lhx = []
lz = []

[dependencies]
chrono = "0.4"
bitflags = "1.2"

[dev-dependencies]
crc-any = "2.3"
rand = "0.7"
