[package]
name = "delharc"
version = "0.1.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2018"
description = "A library for parsing and extracting files from LHA/LZH archive file format."
categories = ["compression"]
keywords = ["LHA", "LZH", "UNLHA"]
homepage = "https://github.com/royaltm/rust-delharc"
repository = "https://github.com/royaltm/rust-delharc"
license = "MIT"
readme = "README.md"
exclude = ["/.travis.yml", ".gitignore", "tests/**/*.{com,bin,run,x,tos,lzh,lzs,exe,rs}"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["lh1", "lz"]
lh1 = []
lhx = []
lz = []

[dependencies]
chrono = "0.4"
bitflags = "1.2"

[dev-dependencies]
crc-any = "2.3"
rand = "0.7"
